### ISSUE TITLE
Pressing "New file" on the list of files results in LUA error

### ISSUE THREAD

**Issue by Titanic4** [llysdal/wire-fpga#1]
When I press "New file" button on the list of files, the editor shows up, however the game complains about LUA error in lua/wire/stools/fpga.lua on line 239. The console output when that happens is as follows: 

[Wire FPGA] [lua/wire/stools/fpga.lua:239](https://github.com/llysdal/wire-fpga/blob/4c167d19d6d4f3cc0aa0d2b42ab47c337f4cc386/lua/wire/stools/fpga.lua#L239): attempt to call method 'NewScript' (a nil value)
  1. DoClick - lua/wire/stools/fpga.lua:239
   2. unknown - lua/vgui/dlabel.lua:237

**Comment by llysdal** [comment]
Thanks for reporting, I think it might just be some leftover code from a previous version. I don't use that feature that much myself, so it probably went untested.

**Comment by llysdal** [comment]
e791901b723bc6293899faf828789f810db7d1fa
Fixed :)
